
spring:
  datasource:
    url: jdbc:h2:mem:db
    username: admin
    password: admin
    initialization-mode: always
    data: classpath:data.sql
    schema: classpath:schema.sql
#  datasource:
#    url: jdbc:sqlserver://localhost;databaseName=test
#    username: sa
#    password: Test@2020
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    initialization-mode: always
#    data: classpath:data.sql
#    schema: classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
server:
  port: 8081
