
spring:
  datasource:
    url: jdbc:h2:mem:db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
server:
  port: 8081
