
spring:
#  datasource:
#    url: jdbc:h2:mem:db
#    username: admin
#    password: admin
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=test
    username: sa
    password: Test@2020
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    initialization-mode: never
    data: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
server:
  port: 8081
